export const GET_COMMENTS = 'GET_COMMENTS';
export const CREATE_COMMENTS = 'CREATE_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const DELETE_COMMENTS = 'DELETE_COMMENTS';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const CLEAR_STORE = 'CLEAR_STORE'
